Add boolean prop, 'openInNewTab' to KExternalLink
learningequality/kolibri-design-system pull request #137
Opened 2020-12-01 03:46 UTC by sairina

**Summary:**
- Added boolean prop `openInNewTab` to `KExternalLink`
- Added `:target` to anchor tag in `<template>` to open up new tab if `openInNewTab` is given `true`

Fixes #94 

**Testing:**
- Tested with Chrome on MacOSX, but not yet with other versions of Kolibri.
![Screen-Recording-2020-11-30-at-7 28 34-PM](https://user-images.githubusercontent.com/13563002/100694128-392ce100-3343-11eb-86e0-497edebe3d5b.gif)

2020-12-01 17:37 UTC, indirectlylit commented on lib/buttons-and-links/KExternalLink.vue
> +      },
```suggestion
      openInNewTab: {
        type: Boolean,
        default: false,
      },
```

Generally in prop definitions you should provide one of either `required: true`, or provide a `default`.

Providing a `default` value ensures the prop value is well-defined when nothing is provided from outside, and makes setting `required: false` superfluous.

2020-12-01 17:40 UTC, indirectlylit commented on docs/rstIconReplacements.txt
> +.. |clipboard| replace:: :raw-html:`<span class="design-system-icon"><svg viewBox="0 0 24 24" role="presentation" focusable="false" width="24" height="24" xmlns="http://www.w3.org/2000/svg"><path d="
@sairina this change wasn't technically part of your PR

@nucleogenesis I think we may not have committed this regenerated file after updating the clipboard icon. We should figure out how to ensure that this gets committed - I could imagine a linter rule for example

2020-12-01 18:23 UTC, indirectlylit commented on docs/rstIconReplacements.txt
> +.. |clipboard| replace:: :raw-html:`<span class="design-system-icon"><svg viewBox="0 0 24 24" role="presentation" focusable="false" width="24" height="24" xmlns="http://www.w3.org/2000/svg"><path d="
opened a new PR to catch this in the future:

https://github.com/learningequality/kolibri-design-system/pull/138

@sairina you can revert the change to this file

2020-12-02 19:39 UTC, indirectlylit commented
This looks good, thanks!

It wasn't in the scope of the original issue, but I'd like to suggest that while we're doing this work, we include an iconographic representation of the "new tab" behavior. We do something similar in the design system itself:

![image](https://user-images.githubusercontent.com/2367265/100922694-0d207580-3493-11eb-877b-d4f36c7c5ba8.png)

thoughts?

2020-12-02 19:54 UTC, nucleogenesis commented
@indirectlylit There is an issue for that https://github.com/learningequality/kolibri-design-system/issues/123 - but the one thing not noted in that issue is that we want it to be conditional upon a prop - and we probably want to default it to not showing.

@sairina maybe we could add the icon. You'll find the name of the icon here: https://kolibri-design-system.netlify.app/icons/#icons that you'll want to pass to the `:icon` prop of `<KIcon>`

Additionally - we'll want to make sure that it displays with the correct color and on the right side of the link (just like in https://github.com/learningequality/kolibri-design-system/issues/123) - but when we're RTL it should show on the left side.

2020-12-02 20:00 UTC, nucleogenesis requested changes
We'll want to also add `rel="noopener noreferrer"` attr to that `<a>` tag for security purposes

https://mathiasbynens.github.io/rel-noopener/ has a great breakdown of why we need to add this to external links.

2020-12-04 04:39 UTC, sairina commented
@nucleogenesis Thanks for that explanation! I'll add that in.
@indirectlylit I'll work on adding the icon!

2021-01-05 17:44 UTC, merged