Add navigateTo listener in KContentRenderer mixin for HTML5 hashi work
learningequality/kolibri-design-system pull request #239
Opened 2021-06-02 14:30 UTC by marcellamaki

## Description

Add navigateTo listener in KContentRenderer mixin for HTML5 hashi work.

## Steps to test

Please see this [kolibri PR for extensions to the navigateTo work](https://github.com/learningequality/kolibri/pull/8134).

2021-06-02 20:39 UTC, sairina approved these changes
LGTM. Seems to be working in the associated [Kolibri PR](https://github.com/learningequality/kolibri/pull/8134).

2021-06-03 23:25 UTC, rtibbles commented on lib/content/mixin.js
> +  'navigateto',
You called your hashi event `navigateto`, but the event you are emitting from the content renderer (which is relevant to this) was called `navigateToRegularContext` https://github.com/learningequality/kolibri/pull/8134/files#diff-cf6ea11127dacf9dddc24383c075d4e76547563841df759b5bbf0962c9293719R127

I certainly prefer `navigateTo` but perhaps with camelCase to be consistent.

2021-06-03 23:26 UTC, rtibbles requested changes
Mismatch between this PR and the Kolibri one.

2022-02-02 22:03 UTC, rtibbles approved these changes

2022-02-02 22:03 UTC, merged