test: add tests for `KImg`
learningequality/kolibri-design-system pull request #518
Opened 2024-01-10 14:39 UTC by EshaanAgg

## Description
Adds tests for the `Kimg` component

#### Issue addressed
Fixes #512 

### Before/after screenshots
NA

## Changelog

- [#PR no]
  - **Description:** Summary of change(s)
  - **Products impact:** Choose from - none (for internal updates) / bugfix / new API / updated API / removed API. If it's 'none', use "-" for all items below to indicate they are not relevant.
  - **Addresses:** Link(s) to GH issue(s) addressed. Include KDS links as well as links to related issues in a consumer product repository too.
  - **Components:** Affected public KDS component. Do not include internal sub-components or documentation components.
  - **Breaking:** Will this change break something in a consumer? Choose from: yes / no
  - **Impacts a11y:** Does this change improve a11y or adds new features that can be used to improve it? Choose from: yes / no
  - **Guidance:** Why and how to introduce this update to a consumer? Required for breaking changes, appreciated for changes with a11y impact, and welcomed for non-breaking changes when relevant.

[#PR no]: [PR link]

## Steps to test

1. Step 1
2. Step 2
3. ...

## (optional) Implementation notes

### At a high level, how did you implement this?

### Does this introduce any tech-debt items?

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [ ] The changelog item has been pasted to the `CHANGELOG.md`

## Comments

2024-01-15 15:34 UTC, MisRob commented
Thanks @EshaanAgg, I will read it in more detail in the next few days, but the scenarios you decided to test and the overall strategy makes sense to me already.

2024-01-18 14:07 UTC, MisRob requested changes
Thanks @EshaanAgg, it's a really good test suite, easy to navigate and understand. Your selection of tests scenarios makes sense to me.

I'd like to request only one change in regards to organization of the test file before merge.

2024-01-18 14:07 UTC, MisRob commented on lib/KImg.spec.js
Could you create a new folder for `KImg` with `__tests__` subfolder and its test suite into there? It's a convention we've been trying to follow. Please also move `KImg.vue` into the folder and rename it to `index.vue`.

`lib/KImg.vue` --> `lib/KImg/index.vue`
`lib/Kimg.spec.js` --> `lib/KImg/__tests__/KImg.spec.js`

 You can see `KTextbox` folder for example.

2024-01-18 16:28 UTC, EshaanAgg commented on lib/KImg.spec.js
Made these changes!

2024-01-18 16:57 UTC, MisRob commented on lib/KImg.spec.js
Thanks, looking good. Would you mind also resolving the conflicts?

2024-01-18 17:22 UTC, EshaanAgg commented on lib/KImg.spec.js
Done!

2024-01-18 18:02 UTC, MisRob approved these changes
Good work, thank you!

2024-01-18 18:02 UTC, merged