Update dropshadows to the latest guidelines
learningequality/kolibri-design-system pull request #736
Opened 2024-08-20 19:23 UTC by lokesh-sagi125

## Description
updating dropshadow according to the latest guidelines and replacing box-shadow eith appropriate dropshadow

#### updated the elemnts in the kds repo to use the dropshadows according to the latest guidelines and replace other elements like boxshadows with appropriate dropshadow.

Addresses #724

## Changelog

- [#735 ]
  - **Description:**  update
  - **Products impact:**  none
  - **Addresses:** Link(s) to GH issue(s) addressed. Include KDS links as well as links to related issues in a consumer product repository too.
  - **Components:** Affected public KDS component. Do not include internal sub-components or documentation components.
  - **Breaking:**  no
  - **Impacts a11y:**  no
  - **Guidance:** .

[#735 ]: https://github.com/learningequality/kolibri-design-system/issues/724

2024-08-21 13:57 UTC, MisRob commented
Thanks @lokesh-sagi125. Did very brief skim and overall it seems to me it does what it's supposed to :) I will invite my colleagues for a full review. Meanwhile, please run `yarn lint-fix` and commit to resolve linting issues.

2024-08-21 14:02 UTC, lokesh-sagi125 commented
yes @MisRob  on it

2024-08-21 18:48 UTC, lokesh-sagi125 commented
hey , just ran yarn-fix and updated the change log, sorry for the inconvenience i am new to contributing

2024-08-21 18:49 UTC, MisRob commented
@lokesh-sagi125 Sure, no problem at all, we're happy to provide guidance to new contributors :) Thanks!

2024-08-21 18:55 UTC, MisRob commented
@lokesh-sagi125 would you be able to resolve the conflict? I think you updated the styling page but I also updated it as part of the writing styling guidance that you followed. I just merged that to `develop` and it caused conflict here. You can just accept changes incoming from develop in _docs/pages/styling/index.vue__ file.

2024-08-21 18:56 UTC, MisRob commented
@lokesh-sagi125 would you be able to resolve the conflict? I think you updated the styling page but I also updated it as part of the writing styling guidance that you followed. I just merged that to `develop` and it caused conflict here. You can resolve by (1) merging the latest upstream `develop` branch to this branch and (2) accept changes incoming from the upstream `develop` in _docs/pages/styling/index.vue__ file.

2024-08-21 19:01 UTC, MisRob commented
@lokesh-sagi125 would you be able to resolve the conflict? I think you updated the styling page but I also updated it as part of the writing styling guidance that you followed. I just merged [my PR](https://github.com/learningequality/kolibri-design-system/pull/723) to `develop` and it caused conflict here. You can resolve by (1) merging the latest upstream `develop` branch to this branch and (2) accept changes incoming from the upstream `develop` in _docs/pages/styling/index.vue__ file. As a result, your PR will contain no changes to _docs/pages/styling/index.vue_.

Thanks for taking care of the file too and sorry I have forgotten to mention this when you picked up the issue.

2024-08-21 19:05 UTC, lokesh-sagi125 commented
@MisRob done with including the changes, can you try merging again?

2024-08-21 19:13 UTC, MisRob commented
I already merged my work @lokesh-sagi125, that's why you saw the conflict. But I see you resolved that now! Looking good, thanks.

2024-08-27 04:34 UTC, lokesh-sagi125 commented
hey @MisRob  is there sth wrong with the pr or can i move on to another issue?

2024-08-27 09:40 UTC, MisRob commented
Hi @lokesh-sagi125, I don't think that anything is wrong :) Seems nobody got to do the review yet. You don't need to wait for a review to be finished to work on another task, so you're welcome to pick something.

2024-08-28 09:57 UTC, akolson requested changes
Hi @lokesh-sagi125! great work on the clean up. As opposed to commenting out the old code, It makes more sense to remove it altogether, as we wont need it :). Based on the acceptance criteria,
> However, the unused %dropshadow-...s shouldn’t be deleted from definitions.scss yet (they are still being referenced from some non-KDS components in the products).

we can safely delete them save for the aforementioned exception.

2024-08-28 21:04 UTC, MisRob commented on CHANGELOG.md
Leaving a note here that before merging it'd be good to revert CHANGELOG.md changes since the new GH action will now update the CHANGELOG.md after merging this PR by pasting the changelog from the PR description. Otherwise we'd have duplicate entries.

2024-08-29 07:01 UTC, MisRob commented
Thanks for following-up @lokesh-sagi125. cc @akolson will leave the final approve on you, just leaving a note that I already updated the changelog description in the PR.

2024-08-29 07:02 UTC, MisRob commented on yarn.lock
Would you revert this @lokesh-sagi125?

2024-08-29 11:12 UTC, akolson requested changes
After the revert of the yarn.lock, we should be good with this. Leaving a blocker here to prevent accidental merge. But all is good. Thanks @lokesh-sagi125 for your contribution!

2024-08-30 06:37 UTC, lokesh-sagi125 commented on yarn.lock
done

2024-08-30 06:42 UTC, akolson commented on yarn.lock
> +    yargs-parser "^20.2.2"
Please remove this added new line that is causing the diff in this file.

2024-08-30 06:43 UTC, akolson commented on yarn.lock
Ideally this file shouldn't be a part of the pr. Could you please do [this](https://github.com/learningequality/kolibri-design-system/pull/736/files#r1738037926) and the revert should be complete. Thanks again @lokesh-sagi125

2024-08-30 08:46 UTC, MisRob commented
Hi @lokesh-sagi125, another way to formulate what we're trying to say with @akolson regarding `yarn.lock` is that when you go to the _Files_ tab in this pull request https://github.com/learningequality/kolibri-design-system/pull/736/files, there should be no `yarn.lock` file present at all. This would cause issues with dependencies.

This is a nice technique for removing file from a pull request https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request

2024-08-30 08:55 UTC, akolson commented on yarn.lock
Hi @lokesh-sagi125  apologies in the back and forth, but this latest change would now break the dependency as  `yargs-parser...` has been removed. Could you please do [this](https://github.com/learningequality/kolibri-design-system/pull/736#issuecomment-2320523084) as suggested by my colleague @MisRob

2024-08-30 10:02 UTC, lokesh-sagi125 commented
the yarn.lock is not getting exclude through git commands , let me re-open the pr , sorry for the inconvenience

2024-08-30 10:05 UTC, akolson commented
@lokesh-sagi125 no need to go through the trouble, we'll fix this on our side. Your pull request almost ready for the merge. Re-opening and reverting the yarn.lock. Thanks Again!

2024-08-30 10:17 UTC, akolson commented
@lokesh-sagi125 I have already made the revert and will be pushing shortly. :)

2024-08-30 10:23 UTC, lokesh-sagi125 commented
hey @akolson @MisRob   sorry i couldn't of much help while fixing the issue, i will make sure to keep these issues in mind for my future contributions , thank you for being supportive :) .

2024-08-30 10:25 UTC, closed without merging

2024-08-30 10:28 UTC, MisRob commented
No problem @lokesh-sagi125, it was just 1 file out of 13 ;)

However I'm sorry to say you've just closed it by deleting your fork, and we can't re-open in this case.

2024-08-30 10:29 UTC, lokesh-sagi125 commented
oh im really sorry about that ; i was on the wrong user let me reopen it

2024-08-30 10:29 UTC, MisRob commented
@lokesh-sagi125 I am pretty sure that was accidental. Just let us know if you wish to open a new PR ;)

2024-08-30 10:29 UTC, MisRob commented
No worries.

2024-08-30 10:29 UTC, MisRob commented
Oh wait, I can perhaps reopen it now.

2024-08-30 10:34 UTC, akolson commented
@lokesh-sagi125 in case it's much of trouble, please let me know as I can create a branch with your changes if necessary. Thanks