remove deprecated dropshadows
learningequality/kolibri-design-system pull request #815
Opened 2024-11-04 11:08 UTC by lokesh-sagi125

## Description
remove deprecated dropshadows

#### Issue addressed
 https://github.com/learningequality/kolibri-design-system/issues/725

Addresses #725 

## Changelog

  - **Description:** removed the deprecated dropshadows
  - **Products impact:**  none
  - **Addresses:** #725 
  - **Components:** -
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:**  -

2024-11-05 06:11 UTC, ozer550 approved these changes

2024-11-05 06:15 UTC, ozer550 submitted a review, later dismissed
I just saw that in the issue description it is mentioned rather to comment these out and not remove them completely.

2024-11-05 07:48 UTC, lokesh-sagi125 commented
oh , sorry about that @ozer550  i got confused and thought its the other way around 😅, just reverted the delete and commented the deprecated dropshadows:).

2024-11-05 13:34 UTC, AlexVelezLl requested changes
Thank you @lokesh-sagi125! These are the right changes for this, however, for now, we are checking if these 3 values ​​1dp, 2dp and 6dp also aligned correctly to Studio's needs, so I will block the merge of this PR for now until we have a final confirmation from our design team :hugs: thank you!

2024-11-13 16:20 UTC, AlexVelezLl reviewed
Alright, it seems that these will work fine with Studio :tada:. Lets just add this comment that was mentioned in the issue,and after that, this should be good to go!

2024-11-13 16:20 UTC, AlexVelezLl commented on lib/styles/definitions.scss
> +// %dropshadow-3dp {
Could we add here a comment indicating that uncommenting needs to be discussed with designers and should be aligned with the guidelines.

2024-11-14 14:04 UTC, AlexVelezLl requested changes
Hey @lokesh-sagi125! Lets remove these extra additions, and after that we can proceed to merge the PR. Thank you!

2024-11-14 14:04 UTC, AlexVelezLl commented on .gitignore
> +package.json
Lets remove this line, please, we need to track the changes of the package.json

2024-11-14 14:04 UTC, AlexVelezLl commented on package.json
> +  "volta": {
In KDS we still use node 10. Please, lets remove this addition

2024-11-14 15:08 UTC, lokesh-sagi125 commented
@AlexVelezLl  just removed the additions

2024-11-15 13:39 UTC, AlexVelezLl approved these changes
Thank you @lokesh-sagi125! This looks good to me, merging :tada:.

2024-11-15 13:41 UTC, merged