#Update Docs for z-index & drop-shadow for better clarity
learningequality/kolibri-design-system pull request #819
Opened 2024-11-08 17:17 UTC by RONAK-AI647

## Description
The Google Material Design elevation image is not relevant to our approach to drop-shadows, so it should be moved down to the "z-index" section where it is more relevant.
#### Issue addressed
#813 

Addresses #*PR# HERE*

### Before/after screenshots

## Changelog

  - **Description:**The dropshadow image is displayed under the z-index section.
  - **Products impact:** updated API
  - **Addresses:** learningequality/kolibri-design-system#813
  - **Components:**  no
  - **Impacts a11y:**no
  - **Guidance:** Clearer guidance reduces the potential for confusion while referring to the drop-shadow docs.

## Steps to test

## (optional) Implementation notes

### At a high level, how did you implement this?

### Does this introduce any tech-debt items?

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Comments
 The google material design elevation image from dropdown menu is shifted to the z-index section as the image is more relevant there.

2024-11-12 21:18 UTC, nucleogenesis requested changes
The documentation changes LGTM - I think that your linting issue might be directly related to the changelog issue -- however, to me your changelog section looks right so I'm wondering if maybe @MisRob might see something I'm missing there.

Thank you @RONAK-AI647 for your work on this!

2024-11-13 10:15 UTC, MisRob commented
I'm not sure why the linter check is failing. Sometimes I need to run `yarn lint-fix` twice. Would you try that @RONAK-AI647 and committed the change? Also it'd be helpful if you could upload your terminal output.

2024-11-13 10:17 UTC, MisRob commented
@RONAK-AI647 @nucleogenesis another issue is that this PR contains updated `yarn.lock` and `package.json`. That will need to be removed before we can merge. This could help @RONAK-AI647 https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request. "Files changed" tab shouldn't contain these two files at all as a result.

2024-11-14 02:23 UTC, RONAK-AI647 commented
@MisRob please take a look what my terminal output is:

![image](https://github.com/user-attachments/assets/04c8f486-84b4-471e-96bd-fef4e9ea5ac2)

2024-11-14 07:10 UTC, MisRob commented
Thank you @RONAK-AI647, I don't understand why that's happening. I could see an update made by the linter 

![Screenshot from 2024-11-14 08-09-28](https://github.com/user-attachments/assets/d73def05-3927-4d83-8dec-30600d9b73eb)

so I went ahead and pushed the change for you.

2024-11-14 07:51 UTC, RONAK-AI647 commented
Thank you @MisRob for the help , the local server is passing the linter check but it is not passing here in the cicd, i was struggling for it so much.

2024-11-14 07:53 UTC, MisRob commented
You're welcome @RONAK-AI647, sorry for the trouble :)

2024-11-18 19:37 UTC, MisRob commented
Anything else here @nucleogenesis or could we merge now?

2024-12-02 16:33 UTC, nucleogenesis approved these changes
Thanks again for this @RONAK-AI647 !

2024-12-02 16:33 UTC, merged