Add KSelect dropdown to the Overlay layer
learningequality/kolibri-design-system pull request #877
Opened 2024-12-20 23:43 UTC by AlexVelezLl

## Description
Finally, a robust solution is proposed to the many known issues with the KSelect dropdown by teleporting KSelect dropdown to the Overlay layer using Popper.

#### Issue addressed

Addresses #324 and #690.

### Before/after screenshots

| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/491ae279-65bd-4cda-8367-7e97125ebe6b) | ![image](https://github.com/user-attachments/assets/df6cd1a2-7ab3-458d-913f-c7a22095712e) | 
| ![image](https://github.com/user-attachments/assets/36b5a073-4d57-4dea-9b87-b4e97c956b45) | ![image](https://github.com/user-attachments/assets/9d5e2d60-3fcd-42e4-bb96-26eb23816cba) | 
| Many more examples to be included | |

## Changelog

  - **Description:** Teleport KSelect dropdown to the Overlay layer using Popper.
  - **Products impact:** bugfix.
  - **Addresses:**https://github.com/learningequality/kolibri-design-system/issues/324, https://github.com/learningequality/kolibri-design-system/issues/690.
  - **Components:** KSelect.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** -.

  - **Description:** Removes internal KModal calculations to modify its content height if it had a KSelect inside.
  - **Products impact:** bugfix.
  - **Addresses:**https://github.com/learningequality/kolibri-design-system/issues/324.
  - **Components:** KModal.
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** -.

## Steps to test

1. Step 1
2. Step 2
3. ...

## (optional) Implementation notes

### At a high level, how did you implement this?

### Does this introduce any tech-debt items?

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Comments

2025-01-20 21:26 UTC, LianaHarris360 requested changes
Thank you for finding a solution to this problem! The code looks good and works correctly in most cases, except on the `MyDownloads.vue` page. The two dropdown menus aren't showing up, and there's an error message in the console related to the `k-overlay` element.

![MydownloadsKSelects](https://github.com/user-attachments/assets/83e41d1b-8bff-44eb-b741-c5955073bafd)
Since there are only issues with these two, I'm not entirely sure if changes need to be made in Kolibri or KDS to fix it. I just wanted to mention it in case the problem can be solved in KDS, and if not, it might be considered a breaking change.

Just a quick note: since `KModal` no longer checks for `KSelect`, I believe we can remove the comment in `lib/KSelect/index.vue` that says, "BELOW: KModal targets KeenUiSelect by using div.ui-select selector" on line 11.

2025-01-20 21:26 UTC, LianaHarris360 commented on lib/_Popper.vue
> +        100,
This is just out of curiosity, but how was the debounce time 100ms determined?

2025-01-21 14:11 UTC, AlexVelezLl commented on lib/_Popper.vue
> +        100,
A 100ms delay is a common choice as it falls within the threshold of the shortest perceivable application response delay, as noted [here](https://stackoverflow.com/questions/536300/what-is-the-shortest-perceivable-application-response-delay). Although it will always depend on the context. If we were debouncing a user keyboard typing action, to lets say, trigger an api request after the user has finished typing we would rather use a >300 ms debounce delay depending on the context https://stackoverflow.com/questions/42361485/how-long-should-you-debounce-text-input.

2025-01-21 14:12 UTC, AlexVelezLl commented
Thanks @LianaHarris360! Yes, that was a problem because the KSelect's were being mounted before the `DOMContentLoaded` event was triggered and by that time, the KOverlay layer werent being mounted yet. This will be fixed when https://github.com/learningequality/kolibri-design-system/pull/879 is merged. Will ping Richard again since we had already agreed that this was the best solution :). I will then rebase this PR to have this fixed.

> Just a quick note: since KModal no longer checks for KSelect, I believe we can remove the comment in lib/KSelect/index.vue that says, "BELOW: KModal targets KeenUiSelect by using div.ui-select selector" on line 11.

Thanks! Just removed it :)

2025-01-21 20:52 UTC, AlexVelezLl commented
I have just rebased the branch with the fix @LianaHarris360! Could you take another look? :)

2025-01-21 21:57 UTC, LianaHarris360 approved these changes
The changes are working as they should and the code logic makes sense, thanks for your work on this! @AlexVelezLl

2025-01-21 21:58 UTC, merged